services:
  db:
    image: postgres:16
    env_file:
      - .env
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: odoo
      POSTGRES_PASSWORD: ${ODOO_DB_PASSWORD:-odoo}
    volumes:
      - odoo-db:/var/lib/postgresql/data
    restart: unless-stopped

  odoo:
    image: odoo:18.0
    depends_on:
      - db
    ports:
      - "8069:8069"
    env_file:
      - .env
    environment:
      HOST: db
      USER: odoo
      PASSWORD: ${ODOO_DB_PASSWORD:-odoo}
      ODOO_ADMIN_PASSWD: ${ODOO_ADMIN_PASSWORD:-admin}
      ODOO_MAZURI_CLIENT_SECRET: ${ODOO_MAZURI_CLIENT_SECRET:-}
    volumes:
      - odoo-data:/var/lib/odoo
      - ./scripts:/mnt/scripts:ro
      - ../custom_addons:/mnt/custom-addons:ro
    command: >
      odoo --config=/etc/odoo/odoo.conf
    configs:
      - source: odoo_conf
        target: /etc/odoo/odoo.conf
    restart: unless-stopped

configs:
  odoo_conf:
    file: ./config/odoo.conf.template


volumes:
  odoo-db:
  odoo-data:
